resources:
  repositories:
    - repository: devops # identifier (A-Z, a-z, 0-9, and underscore)
      type: github # see the following "Type" topic
      name: MobisysGmbh/devops-templates # repository name (format depends on `type`)
      endpoint: MobisysGmbH # name of the service connection to use (for types that aren't Azure Repos)
      ref: refs/heads/release/v1 # defaults to refs/heads/main if ref is not set

trigger: none
pr: none

extends:
  template: /yaml/kickstarter-templates/package-pipeline.yml@devops
  parameters:
    vmImage: ubuntu-latest
    #targetFeed: mobisys
    packageType: npm
    artifactsDirectoryToPublish: $(Build.SourcesDirectory)